name: Issue Manager

on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "done": {
                    "delay": 0,
                    "message": "Danke für den Bug Report/Verbesserungsvorschlag! Das ganze wurde eingebaut/gefixt und der Report/Vorschlag wird jetzt geschlossen"
                },
                "wontdo": {
                    "delay": 0,
                    "message": "Eingebaut/gefixt wird das zwar nicht aber trotzdem danke. Der Report/Vorschlag wird jetzt geschlossen"
                },
                "duplicate": {
                    "delay": 0,
                    "message": "Das wurde schon reportet/vorgeschlagen und wird demnach jetzt geschlossen"
                },
                "invalid": {
                    "delay": 0,
                    "message": "Die Hinweise wurden nicht eingehalten weswegen der Report/Vorschlag geschlossen wird"
                },
                "frage": {
                    "delay": 604800,
                    "message": "Die Frage wurde nicht beantwortet weswegen jetzt der Report/Vorschlag geschlossen wird"
                }
            }
