name: Issue Manager

on:
  schedule:
    - cron: "0 0 * * *"
  issue_comment:
    types:
      - created
      - edited
  issues:
    types:
      - labeled
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  issue-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: tiangolo/issue-manager@0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: >
            {
                "done": {
                    "delay": 0,
                    "message": "Danke für dein Issue! Es wurde eingebaut und der Report wird geschlossen"
                },
                "wontdo": {
                    "delay": 0,
                    "message": "Dein Issue wird nicht eingebaut und demnach jetzt geschlossen"
                },
                "duplicate": {
                    "delay": 0,
                    "message": "Das ist ein Duplikat und wird somit jetzt geschlossen"
                },
                "invalid": {
                    "delay": 0,
                    "message": "Du hast die Hinweise nicht beachtet weswegen dein Issue geschlossen wird"
                },
                "frage": {
                    "delay": 604800,
                    "message": "Du hast die Rückfrage zu lange nicht beantwortet, weswegen dein Report geschlossen wird"
                }
            }
